"""Устал жеска, зачем-то усложнил задачу

Revision ID: 60becdb0c339
Revises: 6396ff7c052d
Create Date: 2024-05-24 14:27:03.509212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60becdb0c339'
down_revision: Union[str, None] = '6396ff7c052d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
